### ISSUE TITLE
No progress in 3 days

### ISSUE THREAD

**Issue by awasum** [studmentor/pythonruphine#3]
You have not contributed anything in 3 days. If it reaches the 5 day. i will delete this repo and remove you from the mentorship program.

**Comment by kengneruphine** [comment]
Am currently doing the exercises of chapter 4 and  i facing some
difficulties
Was suppose to commit this morning but i have not finished the exercisese

**Comment by awasum** [comment]
Commit ASAP as u finish each exercise. Commit daily if possible. U dont have to finish all chapter exercises before committing.
